executable = /home/yxiu/Code/NeUDF/test_neudf.sh
arguments = --gpu 0 --case $(MyArg1)

error = /home/yxiu/Code/NeUDF/logs/test_$(MyArg1).err
output = /home/yxiu/Code/NeUDF/logs/test_$(MyArg1).out
log = /home/yxiu/Code/NeUDF/logs/test_$(MyArg1).log

request_memory = 50000
request_disk = 5G
request_cpus = 6
request_gpus = 1
requirements = TARGET.CUDACapability > 7.5
requirements = TARGET.CUDAGlobalMemoryMb > 10000

queue MyArg1 from /home/yxiu/Code/NeUDF/train_lst.txt
